# Generated by Django 5.2.7 on 2025-10-27 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_category_options_alter_contactinfo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='external_links',
        ),
        migrations.AddField(
            model_name='event',
            name='contact_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.contactinfo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
