# Generated by Django 5.2.7 on 2025-10-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_external_links_event_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_links',
            field=models.URLField(blank=True),
        ),
    ]
