# Generated by Django 5.2.7 on 2025-10-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_external_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admission',
            field=models.TextField(default='Free admission'),
        ),
    ]
